### ISSUE TITLE
Appcenter tizen repo?

### ISSUE THREAD

**Issue by EmilAlipiev** [shulgaalexey/gallery-dotnet-sdk-tizen#15]
Hi, 

Quick question. is that repo not available any longer? https://github.com/microsoft/appcenter-sdk-dotnet/tree/Tizen/Preview
I just saw your name that you were maintaining it but no where this repo can be found.

**Comment by shulgaalexey** [comment]
> Hi,
> 
> Quick question. is that repo not available any longer? https://github.com/microsoft/appcenter-sdk-dotnet/tree/Tizen/Preview
> I just saw your name that you were maintaining it but no where this repo can be found.

Hi,

Thanks for your question!
I am not quite sure about that repo since I left Samsung 3.5 years ago.
(it was join effort of Samsung + Microsoft)

Perhaps it'll make sense to contact Microsoft guys.

**Comment by EmilAlipiev** [comment]
ah ok thanks for the answer. too bad that they retired Tizen
